import { defaultOptions, GenericClusterProvider } from "./generic-cluster-provider";
import * as eks from "aws-cdk-lib/aws-eks-v2";
import { IRole } from "aws-cdk-lib/aws-iam";
import { AutoModeNodeClassSpec, AutoModeNodePoolSpec } from "./types";

export interface AutomodeClusterProviderProps extends Partial<eks.ClusterCommonOptions>{

  id?: string;

  /**
   * @default: ['system,'general-purpose']
   */
  nodePools?: string[];

  /**
   * @default: generated by CDK
   */
  nodeRole?: IRole;

  extraNodePools?: {
    [key: string]: AutoModeNodePoolSpec;
  };

  /**
  * If using custom node classes, you must specify a non default node role.  Otherwise delete will fail (https://github.com/aws/aws-cdk/issues/35475)
  */
  extraNodeClasses?: {
    [key: string]: AutoModeNodeClassSpec;
  };

  tags?: {
    [key: string]: string;
  };

}

export class AutomodeClusterProvider extends GenericClusterProvider {

    constructor(props?: AutomodeClusterProviderProps) {
        super({...defaultOptions, ...props, ...{
              compute: props as Pick<AutomodeClusterProviderProps, "nodePools" | "nodeRole" |"extraNodePools" | "extraNodeClasses">,
              defaultCapacityType: eks.DefaultCapacityType.AUTOMODE
            }
        });
    }
 }

