import { CommonClusterOptions } from "aws-cdk-lib/aws-eks";
import { defaultOptions, GenericClusterProvider } from "./generic-cluster-provider";
import * as eksv2 from "@aws-cdk/aws-eks-v2-alpha"
import { IRole } from "aws-cdk-lib/aws-iam";

export interface AutomodeClusterProviderProps extends Partial<CommonClusterOptions>{

  id?: string,

  /**
   * @default: ['system,'general-purpose']
   */
  nodePools?: string[]

  /**
   * @default: generated by CDK
   */
  nodeRole?: IRole

  tags?: {
    [key: string]: string;
  }

}

export class AutomodeClusterProvider extends GenericClusterProvider {

    constructor(props?: AutomodeClusterProviderProps) {
        super({...defaultOptions, ...props, ...{
              automodeComputeConfig: props as Omit<AutomodeClusterProviderProps, "id" | "tags">,
              defaultCapacityType: eksv2.DefaultCapacityType.AUTOMODE
            }
        });
    }
 }

