version: 0.2
env:
  variables:
    CONTEXT_LOCATION:
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - if [ ! -z "${COMMIT_ID}" ]; then git checkout main; git merge --no-edit ${COMMIT_ID}; fi
      - | 
        git status
        npm install aws-cdk@1.113.0 -g
        npm install
      - >
        # if there's no CDKToolkit stack then bootstrap cdk
        aws cloudformation describe-stacks --stack-name CDKToolkit --region ${AWS_REGION} 
        || CDK_NEW_BOOTSTRAP=1 cdk bootstrap aws://$(aws sts get-caller-identity --output text --query Account --region ${AWS_REGION})/${AWS_REGION}
  pre_build:
    commands:
      - >
        [ -z "$CONTEXT_LOCATION" ] || aws s3 cp $CONTEXT_LOCATION .
      - 
  build:
    commands:
      - cdk deploy --verbose --all --require-approval never
    finally:
      - cdk destroy --verbose --all --force
