name: 'Stale issue & PR handler'
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@main
        id: stale
        with:
          ascending: true
          close-issue-message: 'Issue closed due to inactivity.'
          close-pr-message: 'Pull request closed due to inactivity.'
          days-before-close: 60
          days-before-stale: 90
          stale-issue-label: stale
          stale-pr-label: stale
          # Not stale if have this labels
          exempt-issue-labels: 'bug,enhancement,"feature request"'
          exempt-pr-labels: 'bug,enhancement'
          operations-per-run: 100
          stale-issue-message: |
            This issue has been automatically marked as stale because it has been open 60 days
            with no activity. Remove stale label or comment or this issue will be closed in 10 days
          stale-pr-message: |
            This PR has been automatically marked as stale because it has been open 60 days
            with no activity. Remove stale label or comment or this PR will be closed in 10 days
